# Generated by Django 5.1.1 on 2026-04-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_userinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='bot_feedbac_status_411979_idx',
            old_name='bot_feedback_status_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='bot_feedbac_created_341dec_idx',
            old_name='bot_feedback_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='bot_userint_user_id_87cf44_idx',
            old_name='bot_userinteraction_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='bot_userint_timesta_8990d2_idx',
            old_name='bot_userinteraction_timestamp_idx',
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['comment', 'user', 'reaction_type'], name='bot_reactio_comment_1c64e2_idx'),
        ),
        migrations.AddField(
            model_name='ad',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
