# Generated by Django 5.1.1 on 2026-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_add_ad_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='last_sent_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=10),
        ),
    ]
